DerivedData/mal/Build/Products/Debug/step0_repl: step0_repl/step0_repl/main.m
	xcodebuild -scheme step0_repl -configuration Debug -derivedDataPath DerivedData/mal

DerivedData/mal/Build/Products/Debug/step1_read_print: step1_read_print/step1_read_print/main.m step1_read_print/step1_read_print/MALChunkNode.h step1_read_print/step1_read_print/MALChunkNode.m step1_read_print/step1_read_print/MALChunkNodeScanner.h step1_read_print/step1_read_print/MALChunkNodeScanner.m step1_read_print/step1_read_print/MALConsNode.h step1_read_print/step1_read_print/MALConsNode.m step1_read_print/step1_read_print/MALContainerNode.h step1_read_print/step1_read_print/MALLiteralNode.h step1_read_print/step1_read_print/MALLiteralNode.m step1_read_print/step1_read_print/MALNode.h step1_read_print/step1_read_print/MALQuoteNode.h step1_read_print/step1_read_print/MALQuoteNode.m
	xcodebuild -scheme step1_read_print -configuration Debug -derivedDataPath DerivedData/mal

